# Generated by Django 4.2.3 on 2023-07-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DemoAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demomodel',
            name='price',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
